version: "3.3"

services:
  redis:
    container_name: "redis"
    image: redis:alpine
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: boilerplate-web
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: boilerplate-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
    ports:
      - 33066:3306
    volumes:
      - boilerplate_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  boilerplate_db:
